package data_class_component1_N_functions_37

fun main(){
    val user1 = User("Mohan","Kumar",23)

//  These component1, component2... are generated by kotlin compiler.
    val firstName:String = user1.component1()
    val lastName:String = user1.component2()
    val age:Int = user1.component3();

    println("First Name: $firstName | Last Name: $lastName and Age is $age ")


//  User 2
//  component1, component2... are generated in the way they are defined in the data class, not in the way they are passed.
    var user2 = User(age=24, lastName = "Menon", firstName = "Arun")
    println("User 2")
    println(user2.component1())
    println(user2.component2())
    println(user2.component3())


//  component1, component2... are also used for destructuring.
//  These name can be anything.
    val (component1,component2,component3) = User("Abhishek","Tiwari",34)
    println("$component1 , $component2, $component3")

}


data class User(var firstName:String,var lastName:String,var age:Int)
